sudo: required
services:
  - docker

before_install:
  - docker build -t aniketan/multi-container -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true aniketan/multi-container npm run test -- --coverage

after_success:
  - docker build -t aniketan/multi-client ./client
  - docker build -t aniketan/multi-nginx ./nginx
  - docker build -t aniketan/multi-server ./server
  - docker build -t aniketan/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push aniketan/multi-client
  - docker push aniketan/multi-nginx
  - docker push aniketan/multi-server
  - docker push aniketan/multi-worker
  #login docker cli
  #push images to dockerhub
deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env 
  bucket_name: elasticbeanstalk-us-east-2-617960434725
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY